name: Tagging of repos
on:
  workflow_call:
    inputs:
      TAG:
        description: 'Tag to be published'
        required: true
        type: string
      BODY:
        description: 'Release body message'
        required: true
        default: 'Changes in this Release'
        type: string
      PRE_RELEASE:
        description: 'Pre-release? True/False'
        required: true
        default: False
        type: string
      DRAFT:
        description: 'Draft? True/False'
        required: false
        default: False
        type: string

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.TAG }}
          release_name: ${{ github.event.inputs.TAG }}
          body: |
            ${{ github.event.inputs.BODY }}
          draft: ${{ github.event.inputs.DRAFT }}
          prerelease: ${{fromJSON(github.event.inputs.PRE_RELEASE)}}